#![deny(warnings)]

async fn choose() -> usize {
    runite::select! {
        _ = std::future::pending::<usize>() => 0,
        _ = std::future::pending::<usize>() => 1,
        _ = std::future::pending::<usize>() => 2,
        _ = std::future::pending::<usize>() => 3,
        _ = std::future::pending::<usize>() => 4,
        _ = std::future::pending::<usize>() => 5,
        _ = std::future::pending::<usize>() => 6,
        _ = std::future::pending::<usize>() => 7,
        _ = std::future::pending::<usize>() => 8,
        _ = std::future::pending::<usize>() => 9,
        _ = std::future::pending::<usize>() => 10,
        _ = std::future::pending::<usize>() => 11,
        _ = std::future::pending::<usize>() => 12,
        _ = std::future::pending::<usize>() => 13,
        _ = std::future::pending::<usize>() => 14,
        _ = std::future::pending::<usize>() => 15,
        _ = std::future::pending::<usize>() => 16,
        _ = std::future::pending::<usize>() => 17,
        _ = std::future::pending::<usize>() => 18,
        _ = std::future::pending::<usize>() => 19,
        _ = std::future::pending::<usize>() => 20,
        _ = std::future::pending::<usize>() => 21,
        _ = std::future::pending::<usize>() => 22,
        _ = std::future::pending::<usize>() => 23,
        _ = std::future::pending::<usize>() => 24,
        _ = std::future::pending::<usize>() => 25,
        _ = std::future::pending::<usize>() => 26,
        _ = std::future::pending::<usize>() => 27,
        _ = std::future::pending::<usize>() => 28,
        _ = std::future::pending::<usize>() => 29,
        _ = std::future::pending::<usize>() => 30,
        _ = std::future::pending::<usize>() => 31,
        _ = std::future::pending::<usize>() => 32,
        _ = std::future::pending::<usize>() => 33,
        _ = std::future::pending::<usize>() => 34,
        _ = std::future::pending::<usize>() => 35,
        _ = std::future::pending::<usize>() => 36,
        _ = std::future::pending::<usize>() => 37,
        _ = std::future::pending::<usize>() => 38,
        _ = std::future::pending::<usize>() => 39,
        _ = std::future::pending::<usize>() => 40,
        _ = std::future::pending::<usize>() => 41,
        _ = std::future::pending::<usize>() => 42,
        _ = std::future::pending::<usize>() => 43,
        _ = std::future::pending::<usize>() => 44,
        _ = std::future::pending::<usize>() => 45,
        _ = std::future::pending::<usize>() => 46,
        _ = std::future::pending::<usize>() => 47,
        _ = std::future::pending::<usize>() => 48,
        _ = std::future::pending::<usize>() => 49,
        _ = std::future::pending::<usize>() => 50,
        _ = std::future::pending::<usize>() => 51,
        _ = std::future::pending::<usize>() => 52,
        _ = std::future::pending::<usize>() => 53,
        _ = std::future::pending::<usize>() => 54,
        _ = std::future::pending::<usize>() => 55,
        _ = std::future::pending::<usize>() => 56,
        _ = std::future::pending::<usize>() => 57,
        _ = std::future::pending::<usize>() => 58,
        _ = std::future::pending::<usize>() => 59,
        _ = std::future::pending::<usize>() => 60,
        _ = std::future::pending::<usize>() => 61,
        _ = std::future::pending::<usize>() => 62,
        _ = std::future::pending::<usize>() => 63,
        value = async { 64usize } => value,
    }
}

fn main() {
    let _future = choose();
}
