//! Repository automation for runite.
//!
//! Subcommands:
//!   api-report [--check]   Regenerate `docs/public-api.md` from `cargo public-api`.
//!
//! Run via `mise run api-report` (which makes `cargo-public-api` available).

use std::collections::BTreeMap;
use std::process::{Command, ExitCode};

const CRATE: &str = "runite";
const OUTPUT: &str = "docs/public-api.md";
/// Exact nightly used for rustdoc-JSON generation. Pinned because the rendered
/// item listing varies across rustdoc versions, so an unpinned nightly makes
/// the committed report environment-dependent (local vs CI drift). Bump this
/// deliberately and regenerate the report in the same change.
const RUSTDOC_TOOLCHAIN: &str = "nightly-2026-07-01";
const OMIT: &str = "blanket-impls,auto-trait-impls,auto-derived-impls";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("api-report") => api_report(&args[1..]),
        Some(other) => {
            eprintln!("xtask: unknown subcommand `{other}`");
            usage();
            ExitCode::FAILURE
        }
        None => {
            usage();
            ExitCode::FAILURE
        }
    }
}

fn usage() {
    eprintln!("usage: xtask api-report [--check]");
}

/// Generate the grouped public-API markdown report.
///
/// With `--check`, regenerate in memory and fail (non-zero exit) if the
/// committed `docs/public-api.md` is stale, without writing it.
fn api_report(args: &[String]) -> ExitCode {
    let check = args.iter().any(|a| a == "--check");

    let surface = match run_public_api() {
        Ok(s) => s,
        Err(e) => {
            eprintln!("xtask: {e}");
            return ExitCode::FAILURE;
        }
    };
    let rendered = render(&surface);

    if check {
        let current = std::fs::read_to_string(OUTPUT).unwrap_or_default();
        if current == rendered {
            println!("xtask: {OUTPUT} is up to date");
            return ExitCode::SUCCESS;
        }
        eprintln!(
            "xtask: {OUTPUT} is out of date; run `mise run api-report` and commit the result"
        );
        return ExitCode::FAILURE;
    }

    if let Err(e) = std::fs::write(OUTPUT, &rendered) {
        eprintln!("xtask: failed to write {OUTPUT}: {e}");
        return ExitCode::FAILURE;
    }
    println!("xtask: wrote {OUTPUT}");
    ExitCode::SUCCESS
}

/// Invoke `cargo public-api` and return its flattened item listing.
fn run_public_api() -> Result<String, String> {
    let output = Command::new("cargo")
        // The leading `+<toolchain>` is consumed by rustup's cargo shim, pinning
        // the nightly rustdoc that cargo-public-api shells out to.
        .args([
            &format!("+{RUSTDOC_TOOLCHAIN}"),
            "public-api",
            "--all-features",
            "--omit",
            OMIT,
        ])
        .output()
        .map_err(|e| {
            format!(
                "could not run `cargo public-api` ({e}). Install it via `mise install` \
                 (mise provides the cargo:cargo-public-api tool)."
            )
        })?;

    if !output.status.success() {
        return Err(format!(
            "`cargo public-api` failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Render the flat `cargo public-api` listing as grouped markdown.
fn render(surface: &str) -> String {
    let lines: Vec<&str> = surface
        .lines()
        .map(str::trim_end)
        .filter(|l| !l.is_empty())
        .collect();

    // Collect the set of declared modules so items can snap to the longest
    // declared-module prefix of their path.
    let mut modules: Vec<String> = lines.iter().filter_map(|l| declared_module(l)).collect();
    modules.push(CRATE.to_string());

    let mut groups: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for line in &lines {
        let module = module_of(line, &modules);
        groups.entry(module).or_default().push(line);
    }

    let mut out = String::new();
    out.push_str("# `runite` public API surface\n\n");
    out.push_str(
        "_Generated by `xtask api-report` (`mise run api-report`) from `cargo public-api`, \
         with auto-trait, blanket, and derived impls omitted. Do not edit by hand._\n\n",
    );
    out.push_str(&format!("Total public items: **{}**\n\n", lines.len()));

    out.push_str("## Modules\n\n");
    for (module, items) in &groups {
        let anchor = anchor(module);
        out.push_str(&format!(
            "- [`{module}`](#{anchor}) — {} items\n",
            items.len()
        ));
    }
    out.push('\n');

    for (module, items) in &groups {
        out.push_str(&format!("<a id=\"{}\"></a>\n", anchor(module)));
        out.push_str(&format!("## `{module}`\n\n```rust\n"));
        for item in items {
            out.push_str(item);
            out.push('\n');
        }
        out.push_str("```\n\n");
    }
    out
}

/// If `line` declares a module (`pub mod a::b`), return that module path.
fn declared_module(line: &str) -> Option<String> {
    let rest = line.strip_prefix("pub mod ")?;
    let path = rest.split_whitespace().next().unwrap_or(rest);
    Some(path.to_string())
}

/// Snap an API line to the longest declared module that is a path-prefix of it.
fn module_of(line: &str, modules: &[String]) -> String {
    if let Some(m) = declared_module(line) {
        return m;
    }
    let path = item_path(line);
    let segments: Vec<&str> = path.split("::").collect();
    for end in (1..=segments.len()).rev() {
        let candidate = segments[..end].join("::");
        if modules.contains(&candidate) {
            return candidate;
        }
    }
    CRATE.to_string()
}

/// Extract the fully-qualified `runite::...` path an item line refers to.
fn item_path(line: &str) -> String {
    let needle = format!("{CRATE}::");
    let Some(start) = line.find(&needle) else {
        return CRATE.to_string();
    };
    let tail = &line[start..];
    let end = tail
        .find(|c: char| !(c.is_alphanumeric() || c == '_' || c == ':'))
        .unwrap_or(tail.len());
    // Trim any trailing single colon left by a non-`::` boundary.
    tail[..end].trim_end_matches(':').to_string()
}

/// GitHub-style anchor: drop `::` so links resolve against our explicit `<a id>`.
fn anchor(module: &str) -> String {
    module.replace("::", "")
}
